apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: app-selfsigned-cert-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-selfsigned-cert
  namespace: default
spec:
  isCA: true
  commonName: app-selfsigned-cert
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
