apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-ingress-controller
rules:
  - apiGroups: [""]
    resources: ["services", "configmaps", "nodes", "secrets", "events"]
    verbs: ["get", "list", "watch", "patch", "create"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses", "ingresses", "ingresses/status"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
